version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: message-blaster-localstack
    ports:
      - "4566:4566"   # edge port for all services
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - DEBUG=1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
